
/*Constants for Redux actions and reducers to ensure accuracy*/ 

export const GET_DATA_ACTION_REQUEST = 'GET_DATA_ACTION_REQUEST'
export const GET_DATA_ACTION_FAIL = 'GET_DATA_ACTION_FAIL'
export const GET_DATA_ACTION_SUCCESS = 'GET_DATA_ACTION_SUCCESS'


export const UPDATE_DATE_ACTION_REQUEST = 'UPDATE_DATE_ACTION_REQUEST'
export const UPDATE_DATE_ACTION_FAIL = 'UPDATE_DATE_ACTION_FAIL'
export const UPDATE_DATE_ACTION_SUCCESS = 'UPDATE_DATE_ACTION_SUCCESS'

